name: Deploy Node Application

on:
    push:
        branches:
            - main
            - mern-ec2-docker

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
            - name: Build Docker Image
              run: docker build -t souvik00001/velvetbug-backend .
            - name: Publish Image to docker hub
              run: docker push souvik00001/velvetbug-backend:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull souvik00001/velvetbug-backend:latest
            - name: Stop and remove old container if exists
              run: |
                docker stop nodejs-app-container || true 
                docker rm nodejs-app-container || true
            - name: Run Docker Container
              run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_URL='${{ secrets.MONGO_URL }}' -e PORT='${{ secrets.PORT}}' -e RAZORPAY_KEY_ID='${{ secrets.RAZORPAY_KEY_ID}}' -e RAZORPAY_KEY_SECRET='${{ secrets.RAZORPAY_KEY_SECRET}}' souvik00001/velvetbug-backend:latest